var configuration_pages = {
  // ********** //
  // DEMO TRANS //
  // ********** //
  "Demos Translator" : [
    { 
      "title"         : "Image Copy",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 0,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu",
      "valcpu"        : "",
      "valgpu"        : "&validator=on",  
    },    
    { 
      "title"         : "Event Profiling",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 1,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",   
    },  
    { 
      "title"         : "Attractor Copying",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",   
    },
    { 
      "title"         : "Attractor Attached",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&cpu&interop",
      "gpu"           : "&gpu&interop&filter",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",   
    },
    { 
      "title"         : "DXT Compressor",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 3,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : " ",
      "valcpu"        : "",
      "valgpu"        : "",
    }, 
    { 
      "title"         : "Particles",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 4,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",   
    },    
  ],
  // ************************ //
  // DEMO OPENCL BOOK SAMPLES //
  // ************************ //
  "Demos OpenCL Book Samples" : [
    { 
      "title"         : "Hello World",
      "compatibility" : "[Webkit]",
      "pages"         : "build_book/book",
      "id"            : 0,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",                
    },
    { 
      "title"         : "Convolution",
      "compatibility" : "[Webkit]",
      "pages"         : "build_book/book",
      "id"            : 1,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",                
    },
    { 
      "title"         : "Info",
      "compatibility" : "[Webkit]",
      "pages"         : "build_book/book",
      "id"            : 2,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",               
    },
    { 
      "title"         : "Buffer and Sub-buffer",
      "compatibility" : "[Webkit]",
      "pages"         : "build_book/book",
      "id"            : 3,
      "gl"            : "off",
      "cpu"           : " ",
      "gpu"           : " ",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",                
    },
    { 
      "title"         : "Image Gaussian Blur",
      "compatibility" : "[Webkit]",
      "pages"         : "build_book/book",
      "id"            : 4,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : "&gpu",
      "valcpu"        : "",
      "valgpu"        : "&validator=on",               
    },
    { 
      "title"         : "OpenGL Interop",
      "compatibility" : "[Webkit]",
      "pages"         : "build_book/book",
      "id"            : 5,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",              
    },
    { 
      "title"         : "Vector Add",
      "compatibility" : "[Webkit]",
      "pages"         : "build_book/book",
      "id"            : 6,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",               
    },           
  ],  
  // ******** //
  // DEMO OSX //
  // ******** //
  "Demos OSX" : [
    { 
      "title"         : "Hello World",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 0,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",                
    },
    { 
      "title"         : "Transpose",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 1,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu", 
      "valcpu"        : "",
      "valgpu"        : "&validator=on",               
    },
    { 
      "title"         : "Trajectory",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 2,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu", 
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",               
    },
    { 
      "title"         : "Scan",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 3,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu", 
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",               
    },
    { 
      "title"         : "Reduce Int",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 4,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu&int",  
      "valcpu"        : "",
      "valgpu"        : "&validator=on",              
    },
    { 
      "title"         : "Reduce Float",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 4,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu&float", 
      "valcpu"        : "",
      "valgpu"        : "&validator=on",               
    },
    { 
      "title"         : "Noise Copying",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 5,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",   
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",             
    },
    { 
      "title"         : "Noise Attached",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 5,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : "&gpu&interop", 
      "valcpu"        : "",
      "valgpu"        : "&validator=on",               
    },
    { 
      "title"         : "QJulia Copying",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 6,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : "&gpu",    
      "valcpu"        : "",
      "valgpu"        : "&validator=on",            
    },
    { 
      "title"         : "QJulia Attached",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 6,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : "&gpu&interop",
      "valcpu"        : "",
      "valgpu"        : "&validator=on",                
    },
  ],
  // ********************** //
  // DEMO DAVID BUCCIARELLI //
  // ********************** //
  "Demos David Bucciarelli" : [
    { 
      "title"         : "Mandelbulb",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512",
      "gpu"           : "&0&1&preprocessed_rendering_kernel.cl&512&512",   
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",             
    },
    { 
      "title"         : "QJulia",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 1,
      "gl"            : "on",
      "cpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512",
      "gpu"           : "&0&1&preprocessed_rendering_kernel.cl&512&512",       
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",         
    },
    // caustic.scn / caustic3.scn / complex.scn / cornell_large.scn / cornell.scn /simple.scn
    { 
      "title"         : "SmallPT V1 Caustic",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 3,
      "gl"            : "on",
      "cpu"           : "&0&0&preprocessed_rendering_kernel.cl&512&512&scenes/caustic.scn",
      "gpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512&scenes/caustic.scn",   
      "valcpu"        : "",
      "valgpu"        : "",             
    },
    { 
      "title"         : "SmallPT V1 Complex",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 3,
      "gl"            : "on",
      "cpu"           : "&0&0&preprocessed_rendering_kernel.cl&512&512&scenes/complex.scn",
      "gpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512&scenes/complex.scn", 
      "valcpu"        : "",
      "valgpu"        : "",               
    },
    { 
      "title"         : "SmallPT V2 Cornell Large",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 4,
      "gl"            : "on",
      "cpu"           : "&1&0&0&512&512&scenes/cornell_large.scn",
      "gpu"           : "&0&1&0&512&512&scenes/cornell_large.scn",   
      "valcpu"        : "",
      "valgpu"        : "",             
    },
  ],
  // ************ //
  // DEMO OCLTOYS //
  // ************ //            
  "Demos OCLToys" : [
    { 
      "title"         : "Mandel",
      "compatibility" : "[Webkit]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 1,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS",
      "gpu"           : "&-o&ALL_GPUS",     
      "valcpu"        : "",
      "valgpu"        : "",           
    },
    { 
      "title"         : "JugCLer",
      "compatibility" : "[Webkit]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 0,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS",
      "gpu"           : "&-o&ALL_GPUS",    
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",            
    },
    // caustic.scn / caustic3.scn / cornell_fog.scn / cornell_large.scn / cornell_sss.scn / cornell.scn / simple.scn 
    { 
      "title"         : "SmallPT Caustic 3",
      "compatibility" : "[Webkit]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS&-n&scenes/caustic3.scn",
      "gpu"           : "",         
      "valcpu"        : "",
      "valgpu"        : "",
    },
    { 
      "title"         : "SmallPT Cornell Fog",
      "compatibility" : "[Webkit]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS&-n&scenes/cornell_fog.scn",
      "gpu"           : "",        
      "valcpu"        : "",
      "valgpu"        : "",      
    },
    { 
      "title"         : "SmallPT Cornell sss",
      "compatibility" : "[Webkit]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS&-n&scenes/cornell_sss.scn",
      "gpu"           : "",        
      "valcpu"        : "",
      "valgpu"        : "",
    },
  ],
  // ************ //
  // DEMO NVIDIA  //
  // ************ //         
  "Demos NVIDIA" : [
    { 
      "title"         : "BoxFilter",
      "compatibility" : "[Webkit]",
      "pages"         : "build_nvidia/oclnvidia",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",     
      "valcpu"        : "&validator=on",
      "valgpu"        : "&validator=on",           
    },  
    { 
      "title"         : "NBody",
      "compatibility" : "[Webkit]",
      "pages"         : "build_nvidia/oclnvidia",
      "id"            : 18,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : " ",     
      "valcpu"        : "",
      "valgpu"        : "",           
    }, 
    { 
      "title"         : "Particles",
      "compatibility" : "[Webkit]",
      "pages"         : "build_nvidia/oclnvidia",
      "id"            : 19,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : " ",     
      "valcpu"        : "",
      "valgpu"        : "",           
    },     
    { 
      "title"         : "Recursive Gaussian",
      "compatibility" : "[Webkit]",
      "pages"         : "build_nvidia/oclnvidia",
      "id"            : 23,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : " ",     
      "valcpu"        : "",
      "valgpu"        : "",           
    },   
    { 
      "title"         : "SinWave",
      "compatibility" : "[Webkit]",
      "pages"         : "build_nvidia/oclnvidia",
      "id"            : 26,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : " ",     
      "valcpu"        : "",
      "valgpu"        : "",           
    },    
    { 
      "title"         : "Sobel Filter",
      "compatibility" : "[Webkit]",
      "pages"         : "build_nvidia/oclnvidia",
      "id"            : 29,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : " ",     
      "valcpu"        : "",
      "valgpu"        : "",           
    }, 
  ],
}