var configuration_pages = {
  // ********** //
  // DEMO TRANS //
  // ********** //
  "Demos Translator" : [
    { 
      "title"         : "Hello World",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_trans/translator",
      "id"            : 0,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "val"           : "",
    },
    { 
      "title"         : "Convolution",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_trans/translator",
      "id"            : 1,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "val"           : "",   
    },  
    { 
      "title"         : "Image Copy",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 2,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu",
      "val"           : "",  
    },    
    { 
      "title"         : "Event Profiling",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 3,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "val"           : "",   
    },  
    { 
      "title"         : "Attractor Copying",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 4,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "val"           : "",   
    },
    { 
      "title"         : "Attractor Attached",
      "compatibility" : "[Webkit]",
      "pages"         : "build_trans/translator",
      "id"            : 4,
      "gl"            : "on",
      "cpu"           : "&cpu&interop",
      "gpu"           : "&gpu&interop",
      "val"           : "",   
    },
    { 
      "title"         : "DXT Compressor",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_trans/translator",
      "id"            : 5,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : " ",
      "val"           : "",
    },    
  ],
  // ******** //
  // DEMO OSX //
  // ******** //
  "Demos OSX" : [
    { 
      "title"         : "Hello World",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 0,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",
      "val"           : "",                
    },
    { 
      "title"         : "Transpose",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 1,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu", 
      "val"           : "",               
    },
    /*
    { 
      "title"         : "Trajectory",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 2,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu", 
      "val"           : "",               
    },
    */
    { 
      "title"         : "Scan",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 3,
      "gl"            : "off",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu", 
      "val"           : "",               
    },
    { 
      "title"         : "Reduce Int",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 4,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu&int",  
      "val"           : "",              
    },
    { 
      "title"         : "Reduce Float",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 4,
      "gl"            : "off",
      "cpu"           : "",
      "gpu"           : "&gpu&float", 
      "val"           : "",               
    },
    { 
      "title"         : "Noise Copying",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 5,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu",   
      "val"           : "",             
    },
    { 
      "title"         : "Noise Attached",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 5,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : "&gpu&interop", 
      "val"           : "",               
    },
    { 
      "title"         : "QJulia Copying",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_osx/osxsample",
      "id"            : 6,
      "gl"            : "on",
      "cpu"           : "",
      "gpu"           : "&gpu",    
      "val"           : "",            
    },
    { 
      "title"         : "QJulia Attached",
      "compatibility" : "[Webkit]",
      "pages"         : "build_osx/osxsample",
      "id"            : 6,
      "gl"            : "on",
      "cpu"           : "&cpu",
      "gpu"           : "&gpu&interop",
      "val"           : "",                
    },
  ],
  // ********************** //
  // DEMO DAVID BUCCIARELLI //
  // ********************** //
  "Demos David Bucciarelli" : [
    { 
      "title"         : "Mandelbulb",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 1,
      "gl"            : "on",
      "cpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512",
      "gpu"           : "&0&1&preprocessed_rendering_kernel.cl&512&512",   
      "val"           : "",             
    },
    { 
      "title"         : "QJulia",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512",
      "gpu"           : "&0&1&preprocessed_rendering_kernel.cl&512&512",       
      "val"           : "",         
    },
    // caustic.scn / caustic3.scn / complex.scn / cornell_large.scn / cornell.scn /simple.scn
    { 
      "title"         : "SmallPT V1 Caustic",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 3,
      "gl"            : "on",
      "cpu"           : "&0&0&preprocessed_rendering_kernel.cl&512&512&scenes/caustic.scn",
      "gpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512&scenes/caustic.scn",   
      "val"           : "",             
    },
    { 
      "title"         : "SmallPT V1 Complex",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 3,
      "gl"            : "on",
      "cpu"           : "&0&0&preprocessed_rendering_kernel.cl&512&512&scenes/complex.scn",
      "gpu"           : "&1&0&preprocessed_rendering_kernel.cl&512&512&scenes/complex.scn", 
      "val"           : "",               
    },
    { 
      "title"         : "SmallPT V2 Cornell Large",
      "compatibility" : "[Webkit]",
      "pages"         : "build_davibu/davibu",
      "id"            : 4,
      "gl"            : "on",
      "cpu"           : "&1&0&0&512&512&scenes/cornell_large.scn",
      "gpu"           : "&0&1&0&512&512&scenes/cornell_large.scn",   
      "val"           : "",             
    },
  ],
  // ************ //
  // DEMO OCLTOYS //
  // ************ //            
  "Demos OCLToys" : [
    { 
      "title"         : "Mandel",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 1,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS",
      "gpu"           : "&-o&ALL_GPUS",     
      "val"           : "",           
    },
    { 
      "title"         : "JugCLer",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 0,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS",
      "gpu"           : "&-o&ALL_GPUS",    
      "val"           : "",            
    },
    // caustic.scn / caustic3.scn / cornell_fog.scn / cornell_large.scn / cornell_sss.scn / cornell.scn / simple.scn 
    { 
      "title"         : "SmallPT Caustic 3",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS&-n&scenes/caustic3.scn",
      "gpu"           : "",         
      "val"           : "",
    },
    { 
      "title"         : "SmallPT Cornell Fog",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS&-n&scenes/cornell_fog.scn",
      "gpu"           : "",        
      "val"           : "",      
    },
    { 
      "title"         : "SmallPT Cornell sss",
      "compatibility" : "[Webkit/Firefox]",
      "pages"         : "build_toys/ocltoys",
      "id"            : 2,
      "gl"            : "on",
      "cpu"           : "&-o&ALL_CPUS&-n&scenes/cornell_sss.scn",
      "gpu"           : "",        
      "val"           : "",
    },
  ],
}